# Generated by Django 5.0.14 on 2026-09-24 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('CORTAR', 'Cortar Servicio'), ('REACTIVAR', 'Reactivar Servicio'), ('PAGO', 'Registrar Pago'), ('LOGIN', 'Inicio de Sesion')], db_index=True, max_length=20)),
                ('entidad', models.CharField(db_index=True, max_length=100)),
                ('entidad_id', models.CharField(blank=True, max_length=64)),
                ('detalle', models.TextField(blank=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entidad', 'entidad_id'], name='audit_logs_entidad_115c26_idx')],
            },
        ),
    ]
