# Generated by Django 5.0.14 on 2026-09-24 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mikrotik', '0001_initial'),
        ('olts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaRed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('POTENCIA_BAJA', 'Potencia Optica Baja'), ('OLT_CAIDA', 'OLT Caida'), ('ROUTER_CAIDO', 'Router Caido'), ('ONU_LOS', 'ONU con LOS')], db_index=True, max_length=30)),
                ('severidad', models.CharField(choices=[('INFO', 'Informativa'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Critica')], db_index=True, default='WARNING', max_length=10)),
                ('mensaje', models.TextField()),
                ('resuelta', models.BooleanField(db_index=True, default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('onu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='olts.onu')),
            ],
            options={
                'verbose_name': 'Alerta de Red',
                'verbose_name_plural': 'Alertas de Red',
                'db_table': 'alertas_red',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resuelta', 'severidad'], name='alertas_red_resuelt_af9512_idx')],
            },
        ),
        migrations.CreateModel(
            name='SondeoRed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('WARN', 'Advertencia'), ('DOWN', 'Caido')], db_index=True, max_length=10)),
                ('latencia_ms', models.IntegerField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True)),
                ('olt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sondeos', to='olts.olt')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sondeos', to='mikrotik.routermikrotik')),
            ],
            options={
                'verbose_name': 'Sondeo de Red',
                'verbose_name_plural': 'Sondeos de Red',
                'db_table': 'sondeos_red',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['olt', 'timestamp'], name='sondeos_red_olt_id_2fc17a_idx')],
            },
        ),
    ]
