# Generated by Django 5.0.14 on 2026-09-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('facturacion', '0001_initial'),
        ('olts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='onu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='olts.onu'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='facturacion.planvelocidad'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['cliente', 'estado'], name='servicios_cliente_b59624_idx'),
        ),
    ]
