# Generated by Django 5.0.14 on 2026-09-24 21:33

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=apps.core.fields.EncryptedCharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
    ]
