# Generated by Django 5.0.14 on 2026-09-24 21:43

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_cedula_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=apps.core.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=apps.core.fields.EncryptedCharField(db_index=True, max_length=255),
        ),
    ]
