# Generated by Django 5.0.14 on 2026-09-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_direccion_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
