# Generated by Django 5.0.14 on 2026-09-24 16:29

import apps.core.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('vlan_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)])),
                ('gemport_id', models.IntegerField(default=1)),
                ('profile_id_olt', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Line Profile',
                'verbose_name_plural': 'Line Profiles',
                'db_table': 'line_profiles',
                'ordering': ['olt', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='OLT',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('marca', models.CharField(choices=[('Huawei', 'Huawei'), ('VSOL', 'V-SOL')], max_length=20)),
                ('ip_host', models.GenericIPAddressField()),
                ('puerto_ssh', models.IntegerField(default=22)),
                ('usuario', models.CharField(max_length=50)),
                ('password_encrypted', apps.core.fields.EncryptedCharField(max_length=255)),
                ('enable_password_encrypted', apps.core.fields.EncryptedCharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('estado_ultimo_sondeo', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error de conexion'), ('desconocido', 'Desconocido')], db_index=True, default='desconocido', max_length=20)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'OLT',
                'verbose_name_plural': 'OLTs',
                'db_table': 'olts',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ONU',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sn', models.CharField(db_index=True, max_length=50)),
                ('nombre_cliente', models.CharField(blank=True, max_length=150)),
                ('frame', models.IntegerField(default=0)),
                ('slot', models.IntegerField(default=0)),
                ('puerto', models.IntegerField()),
                ('onu_index', models.IntegerField()),
                ('estado', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('los', 'LOS (Loss of Signal)'), ('unknown', 'Desconocido')], db_index=True, default='offline', max_length=20)),
                ('rx_power_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tx_power_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('distancia_m', models.IntegerField(blank=True, null=True)),
                ('ultima_lectura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ONU',
                'verbose_name_plural': 'ONUs',
                'db_table': 'onus',
                'ordering': ['olt', 'frame', 'slot', 'puerto', 'onu_index'],
            },
        ),
        migrations.CreateModel(
            name='TipoONT',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marca', models.CharField(db_index=True, max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('puertos_ethernet', models.IntegerField(default=1)),
                ('puertos_fxs', models.IntegerField(default=0)),
                ('wifi', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de ONT',
                'verbose_name_plural': 'Tipos de ONT',
                'db_table': 'tipos_ont',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.AddConstraint(
            model_name='olt',
            constraint=models.UniqueConstraint(fields=('ip_host', 'puerto_ssh'), name='uniq_olt_host_puerto'),
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='olt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_profiles', to='olts.olt'),
        ),
        migrations.AddField(
            model_name='onu',
            name='line_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onus', to='olts.lineprofile'),
        ),
        migrations.AddField(
            model_name='onu',
            name='olt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onus', to='olts.olt'),
        ),
        migrations.AddField(
            model_name='onu',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onus', to='facturacion.planvelocidad'),
        ),
        migrations.AddConstraint(
            model_name='tipoont',
            constraint=models.UniqueConstraint(fields=('marca', 'modelo'), name='uniq_tipoont_marca_modelo'),
        ),
        migrations.AddField(
            model_name='onu',
            name='tipo_ont',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onus', to='olts.tipoont'),
        ),
        migrations.AddConstraint(
            model_name='lineprofile',
            constraint=models.UniqueConstraint(fields=('olt', 'nombre'), name='uniq_lineprofile_olt_nombre'),
        ),
        migrations.AddIndex(
            model_name='onu',
            index=models.Index(fields=['olt', 'estado'], name='onus_olt_id_8b2ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='onu',
            index=models.Index(fields=['sn'], name='onus_sn_b8c10a_idx'),
        ),
        migrations.AddConstraint(
            model_name='onu',
            constraint=models.UniqueConstraint(fields=('olt', 'sn'), name='uniq_onu_olt_sn'),
        ),
        migrations.AddConstraint(
            model_name='onu',
            constraint=models.UniqueConstraint(fields=('olt', 'frame', 'slot', 'puerto', 'onu_index'), name='uniq_onu_posicion_fisica'),
        ),
    ]
