# Generated by Django 5.0.14 on 2026-09-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onu',
            name='plan_velocidad',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
