# Generated by Django 5.0.14 on 2026-09-24 16:29

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanVelocidad',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('residencial', 'Residencial'), ('empresarial', 'Empresarial')], db_index=True, default='residencial', max_length=20)),
                ('bajada_kbps', models.IntegerField()),
                ('subida_kbps', models.IntegerField()),
                ('burst_limit', models.CharField(blank=True, max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_incluye_iva', models.BooleanField(default=False)),
                ('traffic_table_index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plan de Velocidad',
                'verbose_name_plural': 'Planes de Velocidad',
                'db_table': 'planes_velocidad',
                'ordering': ['bajada_kbps'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('mes', models.CharField(max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('vencida', 'Vencida'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], db_index=True, default='pendiente', max_length=20)),
                ('xml_sri', apps.core.fields.EncryptedTextField(blank=True)),
                ('clave_acceso', models.CharField(blank=True, db_index=True, max_length=49)),
                ('enviada', models.BooleanField(db_index=True, default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facturas',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aplica_iva', models.BooleanField(default=True)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_factura', to='clientes.servicio')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
                'db_table': 'detalles_factura',
                'ordering': ['factura', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente', 'estado'], name='facturas_cliente_83b2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_vencimiento'], name='facturas_fecha_v_1f52e0_idx'),
        ),
    ]
