# Generated by Django 5.0.14 on 2026-09-24 21:33

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='clave_acceso',
            field=apps.core.fields.EncryptedCharField(blank=True, db_index=True, max_length=255),
        ),
    ]
