# Generated by Django 5.0.14 on 2026-09-24 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionWhatsapp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telefono', models.CharField(db_index=True, max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('PAUSADA', 'Pausada (atencion humana)'), ('CERRADA', 'Cerrada')], db_index=True, default='ACTIVA', max_length=20)),
                ('ultima_actividad', models.DateTimeField(auto_now=True, db_index=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_whatsapp', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Conversacion WhatsApp',
                'verbose_name_plural': 'Conversaciones WhatsApp',
                'db_table': 'conversaciones_whatsapp',
                'ordering': ['-ultima_actividad'],
            },
        ),
        migrations.CreateModel(
            name='MensajeWhatsapp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccion', models.CharField(choices=[('ENTRANTE', 'Entrante'), ('SALIENTE', 'Saliente')], max_length=10)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('PLANTILLA', 'Plantilla'), ('IMAGEN', 'Imagen'), ('DOCUMENTO', 'Documento')], default='TEXTO', max_length=20)),
                ('cuerpo', models.TextField(blank=True)),
                ('wa_message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('LEIDO', 'Leido'), ('FALLIDO', 'Fallido')], default='ENVIADO', max_length=20)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='whatsapp.conversacionwhatsapp')),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'db_table': 'mensajes_whatsapp',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversacionwhatsapp',
            index=models.Index(fields=['telefono', 'estado'], name='conversacio_telefon_b94bae_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajewhatsapp',
            index=models.Index(fields=['conversacion', 'created_at'], name='mensajes_wh_convers_5a1c42_idx'),
        ),
    ]
