# Generated by Django 5.0.14 on 2026-09-24 21:33

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='cuerpo',
            field=apps.core.fields.EncryptedTextField(blank=True),
        ),
    ]
