# Generated by Django 5.0.14 on 2026-09-24 21:43

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_alter_mensajewhatsapp_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacionwhatsapp',
            name='telefono',
            field=apps.core.fields.EncryptedCharField(db_index=True, max_length=255),
        ),
    ]
