# Generated by Django 5.0.14 on 2026-09-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_alter_conversacionwhatsapp_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionwhatsapp',
            name='telefono_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
