# Generated by Django 5.0.14 on 2026-09-24 16:29

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('olts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterMikrotik',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('ip_host', models.GenericIPAddressField()),
                ('modo_api', models.CharField(choices=[('binaria', 'API Binaria (8728)'), ('rest', 'REST API (HTTP/HTTPS)')], default='binaria', max_length=10)),
                ('puerto_api', models.IntegerField(default=8728)),
                ('usa_https', models.BooleanField(default=False)),
                ('usuario', models.CharField(max_length=50)),
                ('password_encrypted', apps.core.fields.EncryptedCharField(max_length=255)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Router MikroTik',
                'verbose_name_plural': 'Routers MikroTik',
                'db_table': 'routers_mikrotik',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FirewallBloqueo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_ip', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('tipo_accion', models.CharField(choices=[('CORTAR_SERVICIO', 'Cortar Servicio'), ('REDIRECCION_PAGO', 'Redireccion de Pago'), ('DROP_FORWARD', 'Drop Forward')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('routeros_id', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('onu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos', to='olts.onu')),
            ],
            options={
                'verbose_name': 'Bloqueo de Firewall',
                'verbose_name_plural': 'Bloqueos de Firewall',
                'db_table': 'firewall_bloqueos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('netmask', models.CharField(default='255.255.255.0', max_length=15)),
                ('interfaz', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('asignada', 'Asignada'), ('reservada', 'Reservada')], db_index=True, default='libre', max_length=20)),
                ('onu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='olts.onu')),
            ],
            options={
                'verbose_name': 'Direccion IP',
                'verbose_name_plural': 'Direcciones IP',
                'db_table': 'ip_addresses',
                'ordering': ['router', 'ip_address'],
            },
        ),
        migrations.AddConstraint(
            model_name='routermikrotik',
            constraint=models.UniqueConstraint(fields=('ip_host', 'puerto_api'), name='uniq_router_host_puerto'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='mikrotik.routermikrotik'),
        ),
        migrations.AddField(
            model_name='firewallbloqueo',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='mikrotik.routermikrotik'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['router', 'estado'], name='ip_addresse_router__555ada_idx'),
        ),
        migrations.AddConstraint(
            model_name='ipaddress',
            constraint=models.UniqueConstraint(fields=('router', 'ip_address'), name='uniq_ip_router_direccion'),
        ),
        migrations.AddIndex(
            model_name='firewallbloqueo',
            index=models.Index(fields=['router', 'activo'], name='firewall_bl_router__efc145_idx'),
        ),
        migrations.AddIndex(
            model_name='firewallbloqueo',
            index=models.Index(fields=['cliente_ip'], name='firewall_bl_cliente_01e605_idx'),
        ),
    ]
