# Generated by Django 5.0.14 on 2026-09-24 21:43

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routermikrotik',
            name='usuario',
            field=apps.core.fields.EncryptedCharField(max_length=255),
        ),
    ]
