# Generated by Django 5.0.14 on 2026-09-24 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('facturacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('tipo_incidencia', models.CharField(choices=[('SIN_SERVICIO_LUZ_ROJA', 'Sin servicio (luz roja / LOS)'), ('SIN_SERVICIO', 'Sin servicio'), ('LENTITUD', 'Lentitud'), ('WIFI', 'Problema de Wi-Fi'), ('FACTURACION', 'Facturacion'), ('OTRO', 'Otro')], db_index=True, max_length=30)),
                ('descripcion_bot', models.TextField(blank=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Critica')], db_index=True, default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], db_index=True, default='ABIERTO', max_length=20)),
                ('adjunto_url', models.URLField(blank=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComentario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cuerpo', models.TextField()),
                ('es_interno', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_ticket', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='soporte.ticket')),
            ],
            options={
                'verbose_name': 'Comentario de Ticket',
                'verbose_name_plural': 'Comentarios de Ticket',
                'db_table': 'ticket_comentarios',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('prospecto_nombre', models.CharField(max_length=150)),
                ('prospecto_cedula', models.CharField(db_index=True, max_length=20)),
                ('prospecto_telefono', models.CharField(db_index=True, max_length=20)),
                ('direccion', models.TextField()),
                ('coordenadas_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('coordenadas_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fecha_programada', models.DateField()),
                ('franja_horaria', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], db_index=True, default='agendada', max_length=20)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalacion_origen', to='clientes.cliente')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalaciones', to='facturacion.planvelocidad')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalaciones_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instalación',
                'verbose_name_plural': 'Instalaciones',
                'db_table': 'instalaciones',
                'ordering': ['fecha_programada', '-created_at'],
                'indexes': [models.Index(fields=['estado', 'fecha_programada'], name='instalacion_estado_600db0_idx'), models.Index(fields=['prospecto_cedula'], name='instalacion_prospec_490679_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado', 'prioridad'], name='tickets_estado_38575d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['cliente', 'estado'], name='tickets_cliente_81bc94_idx'),
        ),
    ]
