# Generated by Django 5.0.14 on 2026-09-24 21:33

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='prospecto_cedula',
            field=apps.core.fields.EncryptedCharField(db_index=True, max_length=255),
        ),
    ]
