# Generated by Django 5.0.14 on 2026-09-24 21:43

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_alter_instalacion_prospecto_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='direccion',
            field=apps.core.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='prospecto_telefono',
            field=apps.core.fields.EncryptedCharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='descripcion_bot',
            field=apps.core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticketcomentario',
            name='cuerpo',
            field=apps.core.fields.EncryptedTextField(),
        ),
    ]
