# Generated by Django 5.0.14 on 2026-09-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0003_alter_instalacion_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='prospecto_cedula_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='instalacion',
            name='prospecto_telefono_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
