# Generated by Django 5.0.14 on 2026-09-24 16:29

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('deposito', 'Deposito'), ('billetera', 'Billetera Digital')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('banco_origen', models.CharField(blank=True, max_length=100)),
                ('num_comprobante', models.CharField(blank=True, db_index=True, max_length=50)),
                ('hash_qr', apps.core.fields.EncryptedCharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente Verificacion'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20)),
                ('acreditado', models.BooleanField(db_index=True, default=False)),
                ('fecha_transaccion', models.DateTimeField()),
                ('verificado_por', models.CharField(blank=True, max_length=50)),
                ('cuenta_destino', models.CharField(blank=True, max_length=50)),
                ('origen', models.CharField(blank=True, max_length=30)),
                ('saldo_restante', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_transaccion'],
            },
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_factura', to='facturacion.factura')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='pagos.pago')),
            ],
            options={
                'verbose_name': 'Aplicacion de Pago',
                'verbose_name_plural': 'Aplicaciones de Pago',
                'db_table': 'pago_factura',
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='facturas',
            field=models.ManyToManyField(related_name='pagos', through='pagos.PagoFactura', to='facturacion.factura'),
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('MORA', 'Mora'), ('MANUAL', 'Manual'), ('SOLICITUD', 'Solicitud del Cliente')], max_length=20)),
                ('ejecutado_por', models.CharField(max_length=50)),
                ('fecha_corte', models.DateTimeField(auto_now_add=True)),
                ('reactivado', models.BooleanField(db_index=True, default=False)),
                ('fecha_reactivacion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Corte de Servicio',
                'verbose_name_plural': 'Cortes de Servicio',
                'db_table': 'cortes',
                'ordering': ['-fecha_corte'],
                'indexes': [models.Index(fields=['cliente', 'reactivado'], name='cortes_cliente_23edc3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pagofactura',
            constraint=models.UniqueConstraint(fields=('pago', 'factura'), name='uniq_pago_factura'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['cliente', 'estado'], name='pagos_cliente_aab17f_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_transaccion'], name='pagos_fecha_t_6e02a8_idx'),
        ),
    ]
