# Generated by Django 5.0.14 on 2026-09-24 21:33

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='banco_origen',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cuenta_destino',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pago',
            name='num_comprobante',
            field=apps.core.fields.EncryptedCharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
    ]
